server:
  port: 8080
  servlet:
    context-path: /searchEngine

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruanjian1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xxx #自行配置
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    cache: false
    prefix: classpath:/template/
    suffix: .html
    encoding: UTF-8
    mode: HTML

  redis:
    database: 0
    port: 6379
    password: xxx #自行配置
    host: localhost

mybatis:
  type-aliases-package: com.hjx.search_engine.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback-spring.xml
